spring:
  application:
    name: musinsa-category-api

  datasource:
    url: jdbc:h2:mem:categorydb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret: musinsa-category-admin-secret-key-for-development
  expiration: 3600000

server:
  port: 8080

logging:
  level:
    root: INFO
    com.musinsa.category: DEBUG
    org.springframework.test: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/musinsa-category-api.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

test-account:
  username: admin
  password: musinsa2025!